### ISSUE TITLE
No longer working as of 1/19/2019.

### ISSUE THREAD

**Issue by drmstwizard** [thorio/kcGrabber#1]
I've always had great success with this script, but it is no longer working as of 1/19/2019. Thanks!

**Comment by thorio** [comment]
Sorry for only responding now, but it works fine for me.
Which feature specifically isn't working for you, and on which show?

**Comment by forcedtomakethis** [comment]
Can confirm no longer working, tried with chrome and firefox, grab elements appear but fails to gather.

**Comment by thorio** [comment]
OK, I figured out your issue:
The shows you're trying to grab are only hosted on googlevideo. The script currently only works on openload. On the bright side, I my other script for kissanime already supports multiple servers, so most of the code is already there.

It might be a while until i get around to porting the new code though, sorry about that.

**Comment by forcedtomakethis** [comment]
@thorio l So far I've seen Google vid and rapidvid being the most used and a lot don't have a openload source but thank you for the support and dedication to this project. 👍

**Comment by thorio** [comment]
Hello again :D

I rewrote the script to work on all the kiss sites.
It also includes the server selector, so it resolves your issue.
Check it out [here](https://github.com/thorio/KGrabber).
